name: ugc-script-splitter
services:
- name: web
  source_dir: /
  github:
    repo: your-username/ugc-script-splitter
    branch: main
    deploy_on_push: true
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
    type: SECRET
  - key: GOOGLE_GEMINI_API_KEY
    value: ${GOOGLE_GEMINI_API_KEY}
    type: SECRET
  - key: KIEAI_API_KEY
    value: ${KIEAI_API_KEY}
    type: SECRET
  - key: RATE_LIMIT_WINDOW_MS
    value: "60000"
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "10"
